# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'
strategy:
  matrix:
    Python37:
      python.version: '3.7'
  maxParallel: 1

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    architecture: 'x64'
  displayName: 'Use Python $(python.version)'

- script: |
    pip install --upgrade pip && pip install strings && pip install robotframework && pip install robotframework-seleniumlibrary && pip install collection && npm install chromedriver
    pip install -r requirements.txt
  displayName: 'Install dependencies'


- powershell: python -m robot -i Smoke tests\test_jupiter_toys.robot
  displayName: 'Run Robot Scripts'
  
